PRAGMA foreign_keys=ON;

-- AWE analytics + Da CROWD Player engagement foundation.
-- Privacy posture: no raw IP addresses are stored. visitor_key is a one-way,
-- peppered digest generated by the Worker.

ALTER TABLE artist_media ADD COLUMN description TEXT;
ALTER TABLE artist_media ADD COLUMN source_name TEXT;
ALTER TABLE artist_media ADD COLUMN source_url TEXT;
ALTER TABLE artist_media ADD COLUMN thumbnail_url TEXT;
ALTER TABLE artist_media ADD COLUMN rights_status TEXT NOT NULL DEFAULT 'unverified';
ALTER TABLE artist_media ADD COLUMN duration_seconds INTEGER;
ALTER TABLE artist_media ADD COLUMN published_at TEXT;

CREATE TABLE IF NOT EXISTS site_visitors (
 visitor_key TEXT PRIMARY KEY,
 first_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 visit_count INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS site_visits (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 visitor_key TEXT NOT NULL,
 path TEXT NOT NULL,
 referrer_host TEXT,
 crown_member_id INTEGER,
 visited_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(visitor_key) REFERENCES site_visitors(visitor_key) ON DELETE CASCADE,
 FOREIGN KEY(crown_member_id) REFERENCES members(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS media_views (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 media_id INTEGER NOT NULL,
 visitor_key TEXT NOT NULL,
 crown_member_id INTEGER,
 session_key TEXT NOT NULL,
 qualified_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(media_id) REFERENCES artist_media(id) ON DELETE CASCADE,
 FOREIGN KEY(crown_member_id) REFERENCES members(id) ON DELETE SET NULL,
 UNIQUE(media_id,session_key)
);

CREATE TABLE IF NOT EXISTS media_comments (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 media_id INTEGER NOT NULL,
 member_id INTEGER NOT NULL,
 body TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'visible',
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(media_id) REFERENCES artist_media(id) ON DELETE CASCADE,
 FOREIGN KEY(member_id) REFERENCES members(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_site_visits_path_time ON site_visits(path,visited_at);
CREATE INDEX IF NOT EXISTS idx_media_views_media_time ON media_views(media_id,qualified_at);
CREATE INDEX IF NOT EXISTS idx_media_comments_media_time ON media_comments(media_id,status,created_at);
