PRAGMA foreign_keys=ON;

-- Tha X Filez final Drive flood.
--
-- Adds the records omitted from the earlier capped Grizz/X folder read:
-- - 112 additional Grizz/X still images
-- - 13 Grizz/X raw videos
-- - 1 dedicated High Alert X Tha God promo video
-- Total new records: 126
--
-- Existing 0018 Drive records are not duplicated.
-- All records launch PUBLIC-first.
-- Raw videos remain generic VIDEO until X classifies interview/BTS/promo/etc.

CREATE TABLE IF NOT EXISTS _dxf_drive_0024(
  external_id TEXT PRIMARY KEY,
  canonical_url TEXT,
  title TEXT NOT NULL,
  media_type TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  description TEXT,
  source_name TEXT,
  source_url TEXT,
  thumbnail_url TEXT,
  file_code TEXT NOT NULL UNIQUE
);

DELETE FROM _dxf_drive_0024;

INSERT INTO _dxf_drive_0024(
  external_id,canonical_url,title,media_type,sort_order,description,
  source_name,source_url,thumbnail_url,file_code
) VALUES
('1yHF2NcRZL2EckXsHJukfj161wpc94Nkb','https://drive.google.com/file/d/1yHF2NcRZL2EckXsHJukfj161wpc94Nkb/view?usp=drivesdk','IMG_5800.JPG','photo',5000,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5800.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1yHF2NcRZL2EckXsHJukfj161wpc94Nkb/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1yHF2NcRZL2EckXsHJukfj161wpc94Nkb&sz=w1600','DXF-1105'),
('1pB8Dp8wCWKss3n0i2mLBdqOD9zgNM1Bv','https://drive.google.com/file/d/1pB8Dp8wCWKss3n0i2mLBdqOD9zgNM1Bv/view?usp=drivesdk','IMG_5804.JPG','photo',5001,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5804.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1pB8Dp8wCWKss3n0i2mLBdqOD9zgNM1Bv/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1pB8Dp8wCWKss3n0i2mLBdqOD9zgNM1Bv&sz=w1600','DXF-1106'),
('1kLTHKjo4rKEdbxcUjb1ySO93-Ph--u8k','https://drive.google.com/file/d/1kLTHKjo4rKEdbxcUjb1ySO93-Ph--u8k/view?usp=drivesdk','IMG_5805.JPG','photo',5002,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5805.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1kLTHKjo4rKEdbxcUjb1ySO93-Ph--u8k/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1kLTHKjo4rKEdbxcUjb1ySO93-Ph--u8k&sz=w1600','DXF-1107'),
('13CPKbgRZl9MzGrGYmrdy9o8IueavObdW','https://drive.google.com/file/d/13CPKbgRZl9MzGrGYmrdy9o8IueavObdW/view?usp=drivesdk','IMG_5807.JPG','photo',5003,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5807.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/13CPKbgRZl9MzGrGYmrdy9o8IueavObdW/view?usp=drivesdk','https://drive.google.com/thumbnail?id=13CPKbgRZl9MzGrGYmrdy9o8IueavObdW&sz=w1600','DXF-1108'),
('18CTdt9_BA3LlMATm_alzLUTteafTJiPF','https://drive.google.com/file/d/18CTdt9_BA3LlMATm_alzLUTteafTJiPF/view?usp=drivesdk','IMG_5810.JPG','photo',5004,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5810.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/18CTdt9_BA3LlMATm_alzLUTteafTJiPF/view?usp=drivesdk','https://drive.google.com/thumbnail?id=18CTdt9_BA3LlMATm_alzLUTteafTJiPF&sz=w1600','DXF-1109'),
('1OSEAWLP9zX0FJBhLKS48-tpMJvwF8DbI','https://drive.google.com/file/d/1OSEAWLP9zX0FJBhLKS48-tpMJvwF8DbI/view?usp=drivesdk','IMG_5811.JPG','photo',5005,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5811.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1OSEAWLP9zX0FJBhLKS48-tpMJvwF8DbI/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1OSEAWLP9zX0FJBhLKS48-tpMJvwF8DbI&sz=w1600','DXF-1110'),
('1-ggy3nl3bzvh1BPiIxOzUwXVi6wALnnE','https://drive.google.com/file/d/1-ggy3nl3bzvh1BPiIxOzUwXVi6wALnnE/view?usp=drivesdk','IMG_5812.JPG','photo',5006,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5812.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1-ggy3nl3bzvh1BPiIxOzUwXVi6wALnnE/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1-ggy3nl3bzvh1BPiIxOzUwXVi6wALnnE&sz=w1600','DXF-1111'),
('1g6zhDhqUw2DtRXZO4jkzC7j056sIO0my','https://drive.google.com/file/d/1g6zhDhqUw2DtRXZO4jkzC7j056sIO0my/view?usp=drivesdk','IMG_5813.JPG','photo',5007,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5813.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1g6zhDhqUw2DtRXZO4jkzC7j056sIO0my/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1g6zhDhqUw2DtRXZO4jkzC7j056sIO0my&sz=w1600','DXF-1112'),
('1c8KsubAygrofZ1SU8q_xJdiEIGW0dOe3','https://drive.google.com/file/d/1c8KsubAygrofZ1SU8q_xJdiEIGW0dOe3/view?usp=drivesdk','IMG_5814.JPG','photo',5008,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5814.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1c8KsubAygrofZ1SU8q_xJdiEIGW0dOe3/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1c8KsubAygrofZ1SU8q_xJdiEIGW0dOe3&sz=w1600','DXF-1113'),
('1FIgY24_MXVQCK7ighF4NMI1ubH2VbaDa','https://drive.google.com/file/d/1FIgY24_MXVQCK7ighF4NMI1ubH2VbaDa/view?usp=drivesdk','IMG_5815.JPG','photo',5009,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5815.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1FIgY24_MXVQCK7ighF4NMI1ubH2VbaDa/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1FIgY24_MXVQCK7ighF4NMI1ubH2VbaDa&sz=w1600','DXF-1114'),
('17qm7YUZ4QwgtJW_KB0BFmt4JdWa2FOh4','https://drive.google.com/file/d/17qm7YUZ4QwgtJW_KB0BFmt4JdWa2FOh4/view?usp=drivesdk','IMG_5816.JPG','photo',5010,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5816.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/17qm7YUZ4QwgtJW_KB0BFmt4JdWa2FOh4/view?usp=drivesdk','https://drive.google.com/thumbnail?id=17qm7YUZ4QwgtJW_KB0BFmt4JdWa2FOh4&sz=w1600','DXF-1115'),
('17BabFVoVmksIQY2eW2LxpKRg1vTKhLl0','https://drive.google.com/file/d/17BabFVoVmksIQY2eW2LxpKRg1vTKhLl0/view?usp=drivesdk','IMG_5817.JPG','photo',5011,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5817.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/17BabFVoVmksIQY2eW2LxpKRg1vTKhLl0/view?usp=drivesdk','https://drive.google.com/thumbnail?id=17BabFVoVmksIQY2eW2LxpKRg1vTKhLl0&sz=w1600','DXF-1116'),
('1LtcRiO1NGOGsSC_8yFd2TBaGKlWcAnAL','https://drive.google.com/file/d/1LtcRiO1NGOGsSC_8yFd2TBaGKlWcAnAL/view?usp=drivesdk','IMG_5818.JPG','photo',5012,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5818.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1LtcRiO1NGOGsSC_8yFd2TBaGKlWcAnAL/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1LtcRiO1NGOGsSC_8yFd2TBaGKlWcAnAL&sz=w1600','DXF-1117'),
('100wIrvzN5shOrGi1LKdnuPCl6xi946ZX','https://drive.google.com/file/d/100wIrvzN5shOrGi1LKdnuPCl6xi946ZX/view?usp=drivesdk','IMG_5819.JPG','photo',5013,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5819.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/100wIrvzN5shOrGi1LKdnuPCl6xi946ZX/view?usp=drivesdk','https://drive.google.com/thumbnail?id=100wIrvzN5shOrGi1LKdnuPCl6xi946ZX&sz=w1600','DXF-1118'),
('1z8L3xThtbmi_uwnmuPnC7BkP5ydocSBH','https://drive.google.com/file/d/1z8L3xThtbmi_uwnmuPnC7BkP5ydocSBH/view?usp=drivesdk','IMG_5820.JPG','photo',5014,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5820.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1z8L3xThtbmi_uwnmuPnC7BkP5ydocSBH/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1z8L3xThtbmi_uwnmuPnC7BkP5ydocSBH&sz=w1600','DXF-1119'),
('1V0ip709d5pWMKAocs1K0l6awABQEWbBV','https://drive.google.com/file/d/1V0ip709d5pWMKAocs1K0l6awABQEWbBV/view?usp=drivesdk','IMG_5821.JPG','photo',5015,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5821.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1V0ip709d5pWMKAocs1K0l6awABQEWbBV/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1V0ip709d5pWMKAocs1K0l6awABQEWbBV&sz=w1600','DXF-1120'),
('1GdNZbVkxlB5QQaHszY4lRX-_lz_Xf17N','https://drive.google.com/file/d/1GdNZbVkxlB5QQaHszY4lRX-_lz_Xf17N/view?usp=drivesdk','IMG_5822.JPG','photo',5016,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5822.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1GdNZbVkxlB5QQaHszY4lRX-_lz_Xf17N/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1GdNZbVkxlB5QQaHszY4lRX-_lz_Xf17N&sz=w1600','DXF-1121'),
('1uavOU3R8-J8kzGzcwV3jab7VtL3vPfLj','https://drive.google.com/file/d/1uavOU3R8-J8kzGzcwV3jab7VtL3vPfLj/view?usp=drivesdk','IMG_5823.JPG','photo',5017,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5823.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1uavOU3R8-J8kzGzcwV3jab7VtL3vPfLj/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1uavOU3R8-J8kzGzcwV3jab7VtL3vPfLj&sz=w1600','DXF-1122'),
('1dkWnzjOEDc4YXiClAGQjeZ7II48fP0fH','https://drive.google.com/file/d/1dkWnzjOEDc4YXiClAGQjeZ7II48fP0fH/view?usp=drivesdk','IMG_5824.JPG','photo',5018,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5824.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1dkWnzjOEDc4YXiClAGQjeZ7II48fP0fH/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1dkWnzjOEDc4YXiClAGQjeZ7II48fP0fH&sz=w1600','DXF-1123'),
('10MConznSonaIonzRP9ZM2yvURRFmR-1T','https://drive.google.com/file/d/10MConznSonaIonzRP9ZM2yvURRFmR-1T/view?usp=drivesdk','IMG_5825.JPG','photo',5019,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5825.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/10MConznSonaIonzRP9ZM2yvURRFmR-1T/view?usp=drivesdk','https://drive.google.com/thumbnail?id=10MConznSonaIonzRP9ZM2yvURRFmR-1T&sz=w1600','DXF-1124'),
('1OGL8i4LqhRqDT4zqmw4LzoonmA65YA2q','https://drive.google.com/file/d/1OGL8i4LqhRqDT4zqmw4LzoonmA65YA2q/view?usp=drivesdk','IMG_5826.JPG','photo',5020,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5826.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1OGL8i4LqhRqDT4zqmw4LzoonmA65YA2q/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1OGL8i4LqhRqDT4zqmw4LzoonmA65YA2q&sz=w1600','DXF-1125'),
('17qC5ymgGVVgQ_IVLc5HQxwGamkp5m9N9','https://drive.google.com/file/d/17qC5ymgGVVgQ_IVLc5HQxwGamkp5m9N9/view?usp=drivesdk','IMG_5827.JPG','photo',5021,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5827.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/17qC5ymgGVVgQ_IVLc5HQxwGamkp5m9N9/view?usp=drivesdk','https://drive.google.com/thumbnail?id=17qC5ymgGVVgQ_IVLc5HQxwGamkp5m9N9&sz=w1600','DXF-1126'),
('1w3kxwzBbB0Vk8cErdPbObcb79NrVmWs4','https://drive.google.com/file/d/1w3kxwzBbB0Vk8cErdPbObcb79NrVmWs4/view?usp=drivesdk','IMG_5828.JPG','photo',5022,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5828.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1w3kxwzBbB0Vk8cErdPbObcb79NrVmWs4/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1w3kxwzBbB0Vk8cErdPbObcb79NrVmWs4&sz=w1600','DXF-1127'),
('1cKUGbDwjR3Qp0Q7Rpt59M1XHFAmrn27f','https://drive.google.com/file/d/1cKUGbDwjR3Qp0Q7Rpt59M1XHFAmrn27f/view?usp=drivesdk','IMG_5829.JPG','photo',5023,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5829.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1cKUGbDwjR3Qp0Q7Rpt59M1XHFAmrn27f/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1cKUGbDwjR3Qp0Q7Rpt59M1XHFAmrn27f&sz=w1600','DXF-1128'),
('1ogyPMcFgssmL9ClJDa3EYQlxWC54bvHt','https://drive.google.com/file/d/1ogyPMcFgssmL9ClJDa3EYQlxWC54bvHt/view?usp=drivesdk','IMG_5830.JPG','photo',5024,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5830.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1ogyPMcFgssmL9ClJDa3EYQlxWC54bvHt/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1ogyPMcFgssmL9ClJDa3EYQlxWC54bvHt&sz=w1600','DXF-1129'),
('16N7-BR_wv5lKVmEUoDlbuiSSRMWlz4c2','https://drive.google.com/file/d/16N7-BR_wv5lKVmEUoDlbuiSSRMWlz4c2/view?usp=drivesdk','IMG_5831.JPG','photo',5025,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5831.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/16N7-BR_wv5lKVmEUoDlbuiSSRMWlz4c2/view?usp=drivesdk','https://drive.google.com/thumbnail?id=16N7-BR_wv5lKVmEUoDlbuiSSRMWlz4c2&sz=w1600','DXF-1130'),
('1yvQvv0QzFfcO2c3J9EQvGkrcsNde0u42','https://drive.google.com/file/d/1yvQvv0QzFfcO2c3J9EQvGkrcsNde0u42/view?usp=drivesdk','IMG_5832.JPG','photo',5026,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5832.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1yvQvv0QzFfcO2c3J9EQvGkrcsNde0u42/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1yvQvv0QzFfcO2c3J9EQvGkrcsNde0u42&sz=w1600','DXF-1131'),
('1cKrelAc1NkhYHs7-1MwUEk2T4wIT-O-H','https://drive.google.com/file/d/1cKrelAc1NkhYHs7-1MwUEk2T4wIT-O-H/view?usp=drivesdk','IMG_5833.JPG','photo',5027,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5833.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1cKrelAc1NkhYHs7-1MwUEk2T4wIT-O-H/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1cKrelAc1NkhYHs7-1MwUEk2T4wIT-O-H&sz=w1600','DXF-1132'),
('1BJN0SD7acJhy6qBsAssyhmpeFr7VCpX_','https://drive.google.com/file/d/1BJN0SD7acJhy6qBsAssyhmpeFr7VCpX_/view?usp=drivesdk','IMG_5834.JPG','photo',5028,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5834.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1BJN0SD7acJhy6qBsAssyhmpeFr7VCpX_/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1BJN0SD7acJhy6qBsAssyhmpeFr7VCpX_&sz=w1600','DXF-1133'),
('16Hcjas89wnAuGvxG-KywGWk4P6GMc2hR','https://drive.google.com/file/d/16Hcjas89wnAuGvxG-KywGWk4P6GMc2hR/view?usp=drivesdk','IMG_5835.JPG','photo',5029,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5835.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/16Hcjas89wnAuGvxG-KywGWk4P6GMc2hR/view?usp=drivesdk','https://drive.google.com/thumbnail?id=16Hcjas89wnAuGvxG-KywGWk4P6GMc2hR&sz=w1600','DXF-1134'),
('19MdD2JaomlE4KFGTaalsG8O4B4O7uhQx','https://drive.google.com/file/d/19MdD2JaomlE4KFGTaalsG8O4B4O7uhQx/view?usp=drivesdk','IMG_5836.JPG','photo',5030,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5836.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/19MdD2JaomlE4KFGTaalsG8O4B4O7uhQx/view?usp=drivesdk','https://drive.google.com/thumbnail?id=19MdD2JaomlE4KFGTaalsG8O4B4O7uhQx&sz=w1600','DXF-1135'),
('1ExwjRLvVEeUfC7pWbYcC1vJhKaDNs4w6','https://drive.google.com/file/d/1ExwjRLvVEeUfC7pWbYcC1vJhKaDNs4w6/view?usp=drivesdk','IMG_5837.JPG','photo',5031,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5837.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1ExwjRLvVEeUfC7pWbYcC1vJhKaDNs4w6/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1ExwjRLvVEeUfC7pWbYcC1vJhKaDNs4w6&sz=w1600','DXF-1136'),
('1KKzzdNSJbcXe_x_SYd9DtkltdMLUZtH_','https://drive.google.com/file/d/1KKzzdNSJbcXe_x_SYd9DtkltdMLUZtH_/view?usp=drivesdk','IMG_5838.JPG','photo',5032,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5838.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1KKzzdNSJbcXe_x_SYd9DtkltdMLUZtH_/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1KKzzdNSJbcXe_x_SYd9DtkltdMLUZtH_&sz=w1600','DXF-1137'),
('1vC6czrNdQpgR3wFtUqSK-aUHShx5owXP','https://drive.google.com/file/d/1vC6czrNdQpgR3wFtUqSK-aUHShx5owXP/view?usp=drivesdk','IMG_5839.JPG','photo',5033,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5839.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1vC6czrNdQpgR3wFtUqSK-aUHShx5owXP/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1vC6czrNdQpgR3wFtUqSK-aUHShx5owXP&sz=w1600','DXF-1138'),
('1vpXXL1iG1jkZKMGneFeNE6UydlxGf0G6','https://drive.google.com/file/d/1vpXXL1iG1jkZKMGneFeNE6UydlxGf0G6/view?usp=drivesdk','IMG_5840.JPG','photo',5034,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5840.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1vpXXL1iG1jkZKMGneFeNE6UydlxGf0G6/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1vpXXL1iG1jkZKMGneFeNE6UydlxGf0G6&sz=w1600','DXF-1139'),
('1p2Fqv1-mbiqzT0kk9_ZNtjBrt3EUMWXF','https://drive.google.com/file/d/1p2Fqv1-mbiqzT0kk9_ZNtjBrt3EUMWXF/view?usp=drivesdk','IMG_5841.JPG','photo',5035,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5841.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1p2Fqv1-mbiqzT0kk9_ZNtjBrt3EUMWXF/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1p2Fqv1-mbiqzT0kk9_ZNtjBrt3EUMWXF&sz=w1600','DXF-1140'),
('14NqaXtXa44HXzyYRJj4x8TbjQ3PJ0A9J','https://drive.google.com/file/d/14NqaXtXa44HXzyYRJj4x8TbjQ3PJ0A9J/view?usp=drivesdk','IMG_5842.JPG','photo',5036,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5842.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/14NqaXtXa44HXzyYRJj4x8TbjQ3PJ0A9J/view?usp=drivesdk','https://drive.google.com/thumbnail?id=14NqaXtXa44HXzyYRJj4x8TbjQ3PJ0A9J&sz=w1600','DXF-1141'),
('1aAhKe0zqdUvq1Jn-yQ3Kz3MKNdadB1U_','https://drive.google.com/file/d/1aAhKe0zqdUvq1Jn-yQ3Kz3MKNdadB1U_/view?usp=drivesdk','IMG_5843.JPG','photo',5037,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5843.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1aAhKe0zqdUvq1Jn-yQ3Kz3MKNdadB1U_/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1aAhKe0zqdUvq1Jn-yQ3Kz3MKNdadB1U_&sz=w1600','DXF-1142'),
('1JfPK3xy28d-wFm13xJxKJW21ng4Qv9TW','https://drive.google.com/file/d/1JfPK3xy28d-wFm13xJxKJW21ng4Qv9TW/view?usp=drivesdk','IMG_5844.JPG','photo',5038,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5844.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1JfPK3xy28d-wFm13xJxKJW21ng4Qv9TW/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1JfPK3xy28d-wFm13xJxKJW21ng4Qv9TW&sz=w1600','DXF-1143'),
('12hn-MOn9kOxOizdgSPEL47BC2ZhiPT3F','https://drive.google.com/file/d/12hn-MOn9kOxOizdgSPEL47BC2ZhiPT3F/view?usp=drivesdk','IMG_5845.JPG','photo',5039,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5845.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/12hn-MOn9kOxOizdgSPEL47BC2ZhiPT3F/view?usp=drivesdk','https://drive.google.com/thumbnail?id=12hn-MOn9kOxOizdgSPEL47BC2ZhiPT3F&sz=w1600','DXF-1144'),
('1zxAFp2Ulgl0ARJltbasysOAlSJXUV4nH','https://drive.google.com/file/d/1zxAFp2Ulgl0ARJltbasysOAlSJXUV4nH/view?usp=drivesdk','IMG_5846.JPG','photo',5040,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5846.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1zxAFp2Ulgl0ARJltbasysOAlSJXUV4nH/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1zxAFp2Ulgl0ARJltbasysOAlSJXUV4nH&sz=w1600','DXF-1145'),
('1lFdvYS1ETpr-GcAhQaydVrz2F_Nas5kp','https://drive.google.com/file/d/1lFdvYS1ETpr-GcAhQaydVrz2F_Nas5kp/view?usp=drivesdk','IMG_5847.JPG','photo',5041,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5847.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1lFdvYS1ETpr-GcAhQaydVrz2F_Nas5kp/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1lFdvYS1ETpr-GcAhQaydVrz2F_Nas5kp&sz=w1600','DXF-1146'),
('1A37xhaLqfktpEM2bBT7IfOiDzIbU55wR','https://drive.google.com/file/d/1A37xhaLqfktpEM2bBT7IfOiDzIbU55wR/view?usp=drivesdk','IMG_5848.JPG','photo',5042,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5848.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1A37xhaLqfktpEM2bBT7IfOiDzIbU55wR/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1A37xhaLqfktpEM2bBT7IfOiDzIbU55wR&sz=w1600','DXF-1147'),
('1UtL2GwKrZouB5TOJJVsUass-x8TZt6Uc','https://drive.google.com/file/d/1UtL2GwKrZouB5TOJJVsUass-x8TZt6Uc/view?usp=drivesdk','IMG_5849.JPG','photo',5043,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5849.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1UtL2GwKrZouB5TOJJVsUass-x8TZt6Uc/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1UtL2GwKrZouB5TOJJVsUass-x8TZt6Uc&sz=w1600','DXF-1148'),
('1kaMBp7a7lsr-pRtAzW76PQ4NucbZ2d7b','https://drive.google.com/file/d/1kaMBp7a7lsr-pRtAzW76PQ4NucbZ2d7b/view?usp=drivesdk','IMG_5850.JPG','photo',5044,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5850.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1kaMBp7a7lsr-pRtAzW76PQ4NucbZ2d7b/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1kaMBp7a7lsr-pRtAzW76PQ4NucbZ2d7b&sz=w1600','DXF-1149'),
('1NdtD56NIWCwQWVbiaLU5eJJ9JY747XKN','https://drive.google.com/file/d/1NdtD56NIWCwQWVbiaLU5eJJ9JY747XKN/view?usp=drivesdk','IMG_5851.JPG','photo',5045,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5851.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1NdtD56NIWCwQWVbiaLU5eJJ9JY747XKN/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1NdtD56NIWCwQWVbiaLU5eJJ9JY747XKN&sz=w1600','DXF-1150'),
('1LuR9g5NPxZv5mAgihsVwSQaj208d6Esb','https://drive.google.com/file/d/1LuR9g5NPxZv5mAgihsVwSQaj208d6Esb/view?usp=drivesdk','IMG_5852.JPG','photo',5046,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5852.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1LuR9g5NPxZv5mAgihsVwSQaj208d6Esb/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1LuR9g5NPxZv5mAgihsVwSQaj208d6Esb&sz=w1600','DXF-1151'),
('1tFk9rn9nxufWvF7s7ZswqEEJhVeuG4Ck','https://drive.google.com/file/d/1tFk9rn9nxufWvF7s7ZswqEEJhVeuG4Ck/view?usp=drivesdk','IMG_5853.JPG','photo',5047,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5853.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1tFk9rn9nxufWvF7s7ZswqEEJhVeuG4Ck/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1tFk9rn9nxufWvF7s7ZswqEEJhVeuG4Ck&sz=w1600','DXF-1152'),
('1Mt62bMI864Feq0lKcBFQG7uMIJce_FUb','https://drive.google.com/file/d/1Mt62bMI864Feq0lKcBFQG7uMIJce_FUb/view?usp=drivesdk','IMG_5854.JPG','photo',5048,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5854.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1Mt62bMI864Feq0lKcBFQG7uMIJce_FUb/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1Mt62bMI864Feq0lKcBFQG7uMIJce_FUb&sz=w1600','DXF-1153'),
('1HTAVXMY8Dv5WGj9fe6Q5EL-Fnq1mbehA','https://drive.google.com/file/d/1HTAVXMY8Dv5WGj9fe6Q5EL-Fnq1mbehA/view?usp=drivesdk','IMG_5855.JPG','photo',5049,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5855.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1HTAVXMY8Dv5WGj9fe6Q5EL-Fnq1mbehA/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1HTAVXMY8Dv5WGj9fe6Q5EL-Fnq1mbehA&sz=w1600','DXF-1154'),
('1r7keUtIVo68jwN7GE4-LslIFOfBrdoVo','https://drive.google.com/file/d/1r7keUtIVo68jwN7GE4-LslIFOfBrdoVo/view?usp=drivesdk','IMG_5856.JPG','photo',5050,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5856.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1r7keUtIVo68jwN7GE4-LslIFOfBrdoVo/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1r7keUtIVo68jwN7GE4-LslIFOfBrdoVo&sz=w1600','DXF-1155'),
('1BOPbcti6TfAAJ2fn2_vm3c41-Zy4UEjx','https://drive.google.com/file/d/1BOPbcti6TfAAJ2fn2_vm3c41-Zy4UEjx/view?usp=drivesdk','IMG_5857.JPG','photo',5051,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5857.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1BOPbcti6TfAAJ2fn2_vm3c41-Zy4UEjx/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1BOPbcti6TfAAJ2fn2_vm3c41-Zy4UEjx&sz=w1600','DXF-1156'),
('1buEqQjH7EqC9tYuqSAkfo0AcOqTqBkIU','https://drive.google.com/file/d/1buEqQjH7EqC9tYuqSAkfo0AcOqTqBkIU/view?usp=drivesdk','IMG_5858.JPG','photo',5052,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5858.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1buEqQjH7EqC9tYuqSAkfo0AcOqTqBkIU/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1buEqQjH7EqC9tYuqSAkfo0AcOqTqBkIU&sz=w1600','DXF-1157'),
('1U1Ng3MumDRon1u20HN6QgWcrx9I0Z1-U','https://drive.google.com/file/d/1U1Ng3MumDRon1u20HN6QgWcrx9I0Z1-U/view?usp=drivesdk','IMG_5859.JPG','photo',5053,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5859.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1U1Ng3MumDRon1u20HN6QgWcrx9I0Z1-U/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1U1Ng3MumDRon1u20HN6QgWcrx9I0Z1-U&sz=w1600','DXF-1158'),
('1lHfFYToezj7K5M7W60mfG_tC_yKE8x_e','https://drive.google.com/file/d/1lHfFYToezj7K5M7W60mfG_tC_yKE8x_e/view?usp=drivesdk','IMG_5860.JPG','photo',5054,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5860.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1lHfFYToezj7K5M7W60mfG_tC_yKE8x_e/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1lHfFYToezj7K5M7W60mfG_tC_yKE8x_e&sz=w1600','DXF-1159'),
('1t3CaA27RXrVr8hq_dTjr_8SYVtMeCKAc','https://drive.google.com/file/d/1t3CaA27RXrVr8hq_dTjr_8SYVtMeCKAc/view?usp=drivesdk','IMG_5861.JPG','photo',5055,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5861.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1t3CaA27RXrVr8hq_dTjr_8SYVtMeCKAc/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1t3CaA27RXrVr8hq_dTjr_8SYVtMeCKAc&sz=w1600','DXF-1160'),
('1q-UxD4GFGCyk5t4O0t9RmVTRZqwHutc-','https://drive.google.com/file/d/1q-UxD4GFGCyk5t4O0t9RmVTRZqwHutc-/view?usp=drivesdk','IMG_5862.JPG','photo',5056,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5862.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1q-UxD4GFGCyk5t4O0t9RmVTRZqwHutc-/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1q-UxD4GFGCyk5t4O0t9RmVTRZqwHutc-&sz=w1600','DXF-1161'),
('1m9UQuTLAXy0UPGN3JLWtZgDx_v6yIfqs','https://drive.google.com/file/d/1m9UQuTLAXy0UPGN3JLWtZgDx_v6yIfqs/view?usp=drivesdk','IMG_5863.JPG','photo',5057,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5863.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1m9UQuTLAXy0UPGN3JLWtZgDx_v6yIfqs/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1m9UQuTLAXy0UPGN3JLWtZgDx_v6yIfqs&sz=w1600','DXF-1162'),
('1MUGeK6q5w2AKcOFdSZZEtVaiEIYjWH7t','https://drive.google.com/file/d/1MUGeK6q5w2AKcOFdSZZEtVaiEIYjWH7t/view?usp=drivesdk','IMG_5864.JPG','photo',5058,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5864.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1MUGeK6q5w2AKcOFdSZZEtVaiEIYjWH7t/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1MUGeK6q5w2AKcOFdSZZEtVaiEIYjWH7t&sz=w1600','DXF-1163'),
('1r5pWLvyPjlnKJ8UxQc2Fq3gl7Yx-ejSs','https://drive.google.com/file/d/1r5pWLvyPjlnKJ8UxQc2Fq3gl7Yx-ejSs/view?usp=drivesdk','IMG_5865.JPG','photo',5059,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5865.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1r5pWLvyPjlnKJ8UxQc2Fq3gl7Yx-ejSs/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1r5pWLvyPjlnKJ8UxQc2Fq3gl7Yx-ejSs&sz=w1600','DXF-1164'),
('1h5EEOLwPvRKzSCKWTib4BBwgH3VHHfuW','https://drive.google.com/file/d/1h5EEOLwPvRKzSCKWTib4BBwgH3VHHfuW/view?usp=drivesdk','IMG_5866.JPG','photo',5060,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5866.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1h5EEOLwPvRKzSCKWTib4BBwgH3VHHfuW/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1h5EEOLwPvRKzSCKWTib4BBwgH3VHHfuW&sz=w1600','DXF-1165'),
('1HYJxBm4pPdE8l-mWg_BlvHDA7ZpDgGGL','https://drive.google.com/file/d/1HYJxBm4pPdE8l-mWg_BlvHDA7ZpDgGGL/view?usp=drivesdk','IMG_5867.JPG','photo',5061,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5867.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1HYJxBm4pPdE8l-mWg_BlvHDA7ZpDgGGL/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1HYJxBm4pPdE8l-mWg_BlvHDA7ZpDgGGL&sz=w1600','DXF-1166'),
('1qArLxQWlgDPIPxZdt60YKHVdtlPht0d0','https://drive.google.com/file/d/1qArLxQWlgDPIPxZdt60YKHVdtlPht0d0/view?usp=drivesdk','IMG_5868.JPG','photo',5062,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5868.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1qArLxQWlgDPIPxZdt60YKHVdtlPht0d0/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1qArLxQWlgDPIPxZdt60YKHVdtlPht0d0&sz=w1600','DXF-1167'),
('1ZEDj2bQ7ChqJPOyDRfF-vviYrLBohNQv','https://drive.google.com/file/d/1ZEDj2bQ7ChqJPOyDRfF-vviYrLBohNQv/view?usp=drivesdk','IMG_5869.JPG','photo',5063,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5869.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1ZEDj2bQ7ChqJPOyDRfF-vviYrLBohNQv/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1ZEDj2bQ7ChqJPOyDRfF-vviYrLBohNQv&sz=w1600','DXF-1168'),
('1-hnKRpNoKMrwb0dJ8slGh4nf241Y9x8q','https://drive.google.com/file/d/1-hnKRpNoKMrwb0dJ8slGh4nf241Y9x8q/view?usp=drivesdk','IMG_5870.JPG','photo',5064,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5870.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1-hnKRpNoKMrwb0dJ8slGh4nf241Y9x8q/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1-hnKRpNoKMrwb0dJ8slGh4nf241Y9x8q&sz=w1600','DXF-1169'),
('1fFJhHCLc9IZAwOMCVr_H5JG3vM_nJw7x','https://drive.google.com/file/d/1fFJhHCLc9IZAwOMCVr_H5JG3vM_nJw7x/view?usp=drivesdk','IMG_5871.JPG','photo',5065,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5871.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1fFJhHCLc9IZAwOMCVr_H5JG3vM_nJw7x/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1fFJhHCLc9IZAwOMCVr_H5JG3vM_nJw7x&sz=w1600','DXF-1170'),
('1eKYsr365Ua9-bovpn70amVDyF8TPU_s0','https://drive.google.com/file/d/1eKYsr365Ua9-bovpn70amVDyF8TPU_s0/view?usp=drivesdk','IMG_5872.JPG','photo',5066,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5872.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1eKYsr365Ua9-bovpn70amVDyF8TPU_s0/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1eKYsr365Ua9-bovpn70amVDyF8TPU_s0&sz=w1600','DXF-1171'),
('1LR0V5V4P8Qt5ewQkiaNxOnISCfa5EYkn','https://drive.google.com/file/d/1LR0V5V4P8Qt5ewQkiaNxOnISCfa5EYkn/view?usp=drivesdk','IMG_5873.JPG','photo',5067,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5873.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1LR0V5V4P8Qt5ewQkiaNxOnISCfa5EYkn/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1LR0V5V4P8Qt5ewQkiaNxOnISCfa5EYkn&sz=w1600','DXF-1172'),
('1yLWTTNc_0KAUq0_O7IircgzeMzKm1tlP','https://drive.google.com/file/d/1yLWTTNc_0KAUq0_O7IircgzeMzKm1tlP/view?usp=drivesdk','IMG_5874.JPG','photo',5068,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5874.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1yLWTTNc_0KAUq0_O7IircgzeMzKm1tlP/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1yLWTTNc_0KAUq0_O7IircgzeMzKm1tlP&sz=w1600','DXF-1173'),
('18q_nFMUZKUIFxFPqMy6607eX2pG4ebtU','https://drive.google.com/file/d/18q_nFMUZKUIFxFPqMy6607eX2pG4ebtU/view?usp=drivesdk','IMG_5875.JPG','photo',5069,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5875.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/18q_nFMUZKUIFxFPqMy6607eX2pG4ebtU/view?usp=drivesdk','https://drive.google.com/thumbnail?id=18q_nFMUZKUIFxFPqMy6607eX2pG4ebtU&sz=w1600','DXF-1174'),
('16ufJUynYA-KLI_gna9qcorAfUVCaCo9u','https://drive.google.com/file/d/16ufJUynYA-KLI_gna9qcorAfUVCaCo9u/view?usp=drivesdk','IMG_5876.JPG','photo',5070,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5876.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/16ufJUynYA-KLI_gna9qcorAfUVCaCo9u/view?usp=drivesdk','https://drive.google.com/thumbnail?id=16ufJUynYA-KLI_gna9qcorAfUVCaCo9u&sz=w1600','DXF-1175'),
('1i5WjdpUM2-_q6S6XOzHOYzQCcC-IvFf2','https://drive.google.com/file/d/1i5WjdpUM2-_q6S6XOzHOYzQCcC-IvFf2/view?usp=drivesdk','IMG_5877.JPG','photo',5071,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5877.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1i5WjdpUM2-_q6S6XOzHOYzQCcC-IvFf2/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1i5WjdpUM2-_q6S6XOzHOYzQCcC-IvFf2&sz=w1600','DXF-1176'),
('1WCMhoeMN8McQQ1OuhE5d6_HcfVq2syt7','https://drive.google.com/file/d/1WCMhoeMN8McQQ1OuhE5d6_HcfVq2syt7/view?usp=drivesdk','IMG_5878.JPG','photo',5072,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5878.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1WCMhoeMN8McQQ1OuhE5d6_HcfVq2syt7/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1WCMhoeMN8McQQ1OuhE5d6_HcfVq2syt7&sz=w1600','DXF-1177'),
('1LpNcO3NeiiF3IYtxvlZZIib7TsPelKXg','https://drive.google.com/file/d/1LpNcO3NeiiF3IYtxvlZZIib7TsPelKXg/view?usp=drivesdk','IMG_5879.JPG','photo',5073,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5879.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1LpNcO3NeiiF3IYtxvlZZIib7TsPelKXg/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1LpNcO3NeiiF3IYtxvlZZIib7TsPelKXg&sz=w1600','DXF-1178'),
('1rCUqiVJMGsHPcQNiVOIoBdEVwx1b8oBQ','https://drive.google.com/file/d/1rCUqiVJMGsHPcQNiVOIoBdEVwx1b8oBQ/view?usp=drivesdk','IMG_5880.JPG','photo',5074,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5880.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1rCUqiVJMGsHPcQNiVOIoBdEVwx1b8oBQ/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1rCUqiVJMGsHPcQNiVOIoBdEVwx1b8oBQ&sz=w1600','DXF-1179'),
('16rYS_DkuBCfDRmVdYurHm7Wcl12LlkyK','https://drive.google.com/file/d/16rYS_DkuBCfDRmVdYurHm7Wcl12LlkyK/view?usp=drivesdk','IMG_5881.JPG','photo',5075,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5881.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/16rYS_DkuBCfDRmVdYurHm7Wcl12LlkyK/view?usp=drivesdk','https://drive.google.com/thumbnail?id=16rYS_DkuBCfDRmVdYurHm7Wcl12LlkyK&sz=w1600','DXF-1180'),
('1HHm3QqtotPNkkrl5oQ5v746rOiYa1f0w','https://drive.google.com/file/d/1HHm3QqtotPNkkrl5oQ5v746rOiYa1f0w/view?usp=drivesdk','IMG_5882.JPG','photo',5076,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5882.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1HHm3QqtotPNkkrl5oQ5v746rOiYa1f0w/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1HHm3QqtotPNkkrl5oQ5v746rOiYa1f0w&sz=w1600','DXF-1181'),
('1JEDKHfxFnEN-_S9HubW0cqZgztxQ_Y6V','https://drive.google.com/file/d/1JEDKHfxFnEN-_S9HubW0cqZgztxQ_Y6V/view?usp=drivesdk','IMG_5883.JPG','photo',5077,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5883.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1JEDKHfxFnEN-_S9HubW0cqZgztxQ_Y6V/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1JEDKHfxFnEN-_S9HubW0cqZgztxQ_Y6V&sz=w1600','DXF-1182'),
('1HRQQd3V2toCWgrsnNz1MTHyApXxOYhqo','https://drive.google.com/file/d/1HRQQd3V2toCWgrsnNz1MTHyApXxOYhqo/view?usp=drivesdk','IMG_5884.JPG','photo',5078,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5884.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1HRQQd3V2toCWgrsnNz1MTHyApXxOYhqo/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1HRQQd3V2toCWgrsnNz1MTHyApXxOYhqo&sz=w1600','DXF-1183'),
('1Q_7D0v2durp3p8vkOrvBTXZJ9MAojFpG','https://drive.google.com/file/d/1Q_7D0v2durp3p8vkOrvBTXZJ9MAojFpG/view?usp=drivesdk','IMG_5885.JPG','photo',5079,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5885.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1Q_7D0v2durp3p8vkOrvBTXZJ9MAojFpG/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1Q_7D0v2durp3p8vkOrvBTXZJ9MAojFpG&sz=w1600','DXF-1184'),
('1pAaIqyGkeY9VLmsRIKRBxLrqeR3_KwMv','https://drive.google.com/file/d/1pAaIqyGkeY9VLmsRIKRBxLrqeR3_KwMv/view?usp=drivesdk','IMG_5886.JPG','photo',5080,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5886.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1pAaIqyGkeY9VLmsRIKRBxLrqeR3_KwMv/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1pAaIqyGkeY9VLmsRIKRBxLrqeR3_KwMv&sz=w1600','DXF-1185'),
('1TEXcxpVI3z7gFoykb0uM3AZObxGODwc9','https://drive.google.com/file/d/1TEXcxpVI3z7gFoykb0uM3AZObxGODwc9/view?usp=drivesdk','IMG_5887.JPG','photo',5081,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5887.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1TEXcxpVI3z7gFoykb0uM3AZObxGODwc9/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1TEXcxpVI3z7gFoykb0uM3AZObxGODwc9&sz=w1600','DXF-1186'),
('1xWvTNMs3M30JQHu0Z6rmcbyYvCO4pyHj','https://drive.google.com/file/d/1xWvTNMs3M30JQHu0Z6rmcbyYvCO4pyHj/view?usp=drivesdk','IMG_5888.JPG','photo',5082,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5888.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1xWvTNMs3M30JQHu0Z6rmcbyYvCO4pyHj/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1xWvTNMs3M30JQHu0Z6rmcbyYvCO4pyHj&sz=w1600','DXF-1187'),
('1VXWTJLFNeyt_nKpUNkVegsHZD3qzfWCS','https://drive.google.com/file/d/1VXWTJLFNeyt_nKpUNkVegsHZD3qzfWCS/view?usp=drivesdk','IMG_5889.JPG','photo',5083,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5889.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1VXWTJLFNeyt_nKpUNkVegsHZD3qzfWCS/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1VXWTJLFNeyt_nKpUNkVegsHZD3qzfWCS&sz=w1600','DXF-1188'),
('1wnrDEezvtH55nLqbAmYODuq8pzp3UOZu','https://drive.google.com/file/d/1wnrDEezvtH55nLqbAmYODuq8pzp3UOZu/view?usp=drivesdk','IMG_5890.JPG','photo',5084,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5890.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1wnrDEezvtH55nLqbAmYODuq8pzp3UOZu/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1wnrDEezvtH55nLqbAmYODuq8pzp3UOZu&sz=w1600','DXF-1189'),
('13ZenQKyVaMUEuHOuJ_sU21dYdNH-JinJ','https://drive.google.com/file/d/13ZenQKyVaMUEuHOuJ_sU21dYdNH-JinJ/view?usp=drivesdk','IMG_5891.JPG','photo',5085,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5891.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/13ZenQKyVaMUEuHOuJ_sU21dYdNH-JinJ/view?usp=drivesdk','https://drive.google.com/thumbnail?id=13ZenQKyVaMUEuHOuJ_sU21dYdNH-JinJ&sz=w1600','DXF-1190'),
('1JB4A9KwRR4wAuIcglPIQm6SSYu0zAA3t','https://drive.google.com/file/d/1JB4A9KwRR4wAuIcglPIQm6SSYu0zAA3t/view?usp=drivesdk','IMG_5892.JPG','photo',5086,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5892.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1JB4A9KwRR4wAuIcglPIQm6SSYu0zAA3t/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1JB4A9KwRR4wAuIcglPIQm6SSYu0zAA3t&sz=w1600','DXF-1191'),
('1phQiUYZYRdML2euQluKp8X19DNxDTXIn','https://drive.google.com/file/d/1phQiUYZYRdML2euQluKp8X19DNxDTXIn/view?usp=drivesdk','IMG_5893.JPG','photo',5087,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5893.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1phQiUYZYRdML2euQluKp8X19DNxDTXIn/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1phQiUYZYRdML2euQluKp8X19DNxDTXIn&sz=w1600','DXF-1192'),
('1M0yNJtFcDcswb-QLty1tf7mioDdLFLWv','https://drive.google.com/file/d/1M0yNJtFcDcswb-QLty1tf7mioDdLFLWv/view?usp=drivesdk','IMG_5894.JPG','photo',5088,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5894.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1M0yNJtFcDcswb-QLty1tf7mioDdLFLWv/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1M0yNJtFcDcswb-QLty1tf7mioDdLFLWv&sz=w1600','DXF-1193'),
('14vXyXrxaavVwNVdVl9iEgGvN3Yq9M_2u','https://drive.google.com/file/d/14vXyXrxaavVwNVdVl9iEgGvN3Yq9M_2u/view?usp=drivesdk','IMG_5895.JPG','photo',5089,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5895.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/14vXyXrxaavVwNVdVl9iEgGvN3Yq9M_2u/view?usp=drivesdk','https://drive.google.com/thumbnail?id=14vXyXrxaavVwNVdVl9iEgGvN3Yq9M_2u&sz=w1600','DXF-1194'),
('1-GHf9paNhnhvR3VRLZUy8336yahJSCbg','https://drive.google.com/file/d/1-GHf9paNhnhvR3VRLZUy8336yahJSCbg/view?usp=drivesdk','IMG_5896.JPG','photo',5090,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5896.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1-GHf9paNhnhvR3VRLZUy8336yahJSCbg/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1-GHf9paNhnhvR3VRLZUy8336yahJSCbg&sz=w1600','DXF-1195'),
('1C_N12uS1Zczn5sQmd4FOUkg0PRLEBuLK','https://drive.google.com/file/d/1C_N12uS1Zczn5sQmd4FOUkg0PRLEBuLK/view?usp=drivesdk','IMG_5897.JPG','photo',5091,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5897.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1C_N12uS1Zczn5sQmd4FOUkg0PRLEBuLK/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1C_N12uS1Zczn5sQmd4FOUkg0PRLEBuLK&sz=w1600','DXF-1196'),
('1PZij9aRGz8a0wxqZ01zZwhRe1A2HQX0I','https://drive.google.com/file/d/1PZij9aRGz8a0wxqZ01zZwhRe1A2HQX0I/view?usp=drivesdk','IMG_5898.JPG','photo',5092,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5898.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1PZij9aRGz8a0wxqZ01zZwhRe1A2HQX0I/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1PZij9aRGz8a0wxqZ01zZwhRe1A2HQX0I&sz=w1600','DXF-1197'),
('1AaxudXH7T5O-3YBJRbqQDKaQCmkY4sWT','https://drive.google.com/file/d/1AaxudXH7T5O-3YBJRbqQDKaQCmkY4sWT/view?usp=drivesdk','IMG_5899.JPG','photo',5093,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5899.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1AaxudXH7T5O-3YBJRbqQDKaQCmkY4sWT/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1AaxudXH7T5O-3YBJRbqQDKaQCmkY4sWT&sz=w1600','DXF-1198'),
('15eie8gk9gcX3CU3x1zAEBSwJ3VzUJzoy','https://drive.google.com/file/d/15eie8gk9gcX3CU3x1zAEBSwJ3VzUJzoy/view?usp=drivesdk','IMG_5900.JPG','photo',5094,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5900.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/15eie8gk9gcX3CU3x1zAEBSwJ3VzUJzoy/view?usp=drivesdk','https://drive.google.com/thumbnail?id=15eie8gk9gcX3CU3x1zAEBSwJ3VzUJzoy&sz=w1600','DXF-1199'),
('1sFxQvn9ZqwuvERuvnpkexHXPV8Qp6Ewx','https://drive.google.com/file/d/1sFxQvn9ZqwuvERuvnpkexHXPV8Qp6Ewx/view?usp=drivesdk','IMG_5901.JPG','photo',5095,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5901.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1sFxQvn9ZqwuvERuvnpkexHXPV8Qp6Ewx/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1sFxQvn9ZqwuvERuvnpkexHXPV8Qp6Ewx&sz=w1600','DXF-1200'),
('1ADKXNEX4tRc31XKNoWw3gNFu26kQc-5Q','https://drive.google.com/file/d/1ADKXNEX4tRc31XKNoWw3gNFu26kQc-5Q/view?usp=drivesdk','IMG_5902.JPG','photo',5096,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5902.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1ADKXNEX4tRc31XKNoWw3gNFu26kQc-5Q/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1ADKXNEX4tRc31XKNoWw3gNFu26kQc-5Q&sz=w1600','DXF-1201'),
('1YBg98zNdau1aDQz0KSDNot30G5PZD142','https://drive.google.com/file/d/1YBg98zNdau1aDQz0KSDNot30G5PZD142/view?usp=drivesdk','IMG_5903.JPG','photo',5097,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5903.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1YBg98zNdau1aDQz0KSDNot30G5PZD142/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1YBg98zNdau1aDQz0KSDNot30G5PZD142&sz=w1600','DXF-1202'),
('14JEAjKqCI7RQXeqtUsE5NRWSATXXg9Dd','https://drive.google.com/file/d/14JEAjKqCI7RQXeqtUsE5NRWSATXXg9Dd/view?usp=drivesdk','IMG_5904.JPG','photo',5098,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5904.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/14JEAjKqCI7RQXeqtUsE5NRWSATXXg9Dd/view?usp=drivesdk','https://drive.google.com/thumbnail?id=14JEAjKqCI7RQXeqtUsE5NRWSATXXg9Dd&sz=w1600','DXF-1203'),
('1-vU7d3ZP44nn4IH9ty74OqQeGzVwsIDO','https://drive.google.com/file/d/1-vU7d3ZP44nn4IH9ty74OqQeGzVwsIDO/view?usp=drivesdk','IMG_5905.JPG','photo',5099,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5905.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1-vU7d3ZP44nn4IH9ty74OqQeGzVwsIDO/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1-vU7d3ZP44nn4IH9ty74OqQeGzVwsIDO&sz=w1600','DXF-1204'),
('15DOfYZTG1tJQor4TMZoKoXPNdTNpjyJO','https://drive.google.com/file/d/15DOfYZTG1tJQor4TMZoKoXPNdTNpjyJO/view?usp=drivesdk','IMG_5906.JPG','photo',5100,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5906.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/15DOfYZTG1tJQor4TMZoKoXPNdTNpjyJO/view?usp=drivesdk','https://drive.google.com/thumbnail?id=15DOfYZTG1tJQor4TMZoKoXPNdTNpjyJO&sz=w1600','DXF-1205'),
('1jsYu1uEovJDxn-mhiZvNycylEE7sGXmb','https://drive.google.com/file/d/1jsYu1uEovJDxn-mhiZvNycylEE7sGXmb/view?usp=drivesdk','IMG_5907.JPG','photo',5101,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5907.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1jsYu1uEovJDxn-mhiZvNycylEE7sGXmb/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1jsYu1uEovJDxn-mhiZvNycylEE7sGXmb&sz=w1600','DXF-1206'),
('1iiqCiEowfpfWe8lcc_MY9paBwyoq7VzU','https://drive.google.com/file/d/1iiqCiEowfpfWe8lcc_MY9paBwyoq7VzU/view?usp=drivesdk','IMG_5908.JPG','photo',5102,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5908.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1iiqCiEowfpfWe8lcc_MY9paBwyoq7VzU/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1iiqCiEowfpfWe8lcc_MY9paBwyoq7VzU&sz=w1600','DXF-1207'),
('1RAZtjislMm9Y1OQeCDfWZLR6sH9-ZWbE','https://drive.google.com/file/d/1RAZtjislMm9Y1OQeCDfWZLR6sH9-ZWbE/view?usp=drivesdk','IMG_5909.JPG','photo',5103,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5909.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1RAZtjislMm9Y1OQeCDfWZLR6sH9-ZWbE/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1RAZtjislMm9Y1OQeCDfWZLR6sH9-ZWbE&sz=w1600','DXF-1208'),
('1E88xkR8BW1iIVJHvHeiNjXhmrAyA6BGo','https://drive.google.com/file/d/1E88xkR8BW1iIVJHvHeiNjXhmrAyA6BGo/view?usp=drivesdk','IMG_5910.JPG','photo',5104,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5910.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1E88xkR8BW1iIVJHvHeiNjXhmrAyA6BGo/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1E88xkR8BW1iIVJHvHeiNjXhmrAyA6BGo&sz=w1600','DXF-1209'),
('1jrqDtzpEyWdsvdPPmmP0k6JBW4Ku-YIR','https://drive.google.com/file/d/1jrqDtzpEyWdsvdPPmmP0k6JBW4Ku-YIR/view?usp=drivesdk','IMG_5911.JPG','photo',5105,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5911.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1jrqDtzpEyWdsvdPPmmP0k6JBW4Ku-YIR/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1jrqDtzpEyWdsvdPPmmP0k6JBW4Ku-YIR&sz=w1600','DXF-1210'),
('17-2No1o61cfhBa9gLY02OMnJo8PV6cEa','https://drive.google.com/file/d/17-2No1o61cfhBa9gLY02OMnJo8PV6cEa/view?usp=drivesdk','IMG_5912.JPG','photo',5106,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5912.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/17-2No1o61cfhBa9gLY02OMnJo8PV6cEa/view?usp=drivesdk','https://drive.google.com/thumbnail?id=17-2No1o61cfhBa9gLY02OMnJo8PV6cEa&sz=w1600','DXF-1211'),
('1SSvRWkojL9MuCW2hkI-iocd15kzjR9rH','https://drive.google.com/file/d/1SSvRWkojL9MuCW2hkI-iocd15kzjR9rH/view?usp=drivesdk','IMG_5913.JPG','photo',5107,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5913.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1SSvRWkojL9MuCW2hkI-iocd15kzjR9rH/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1SSvRWkojL9MuCW2hkI-iocd15kzjR9rH&sz=w1600','DXF-1212'),
('1JWCakoyIsDqppBmDlsSwUxdMnCWg9WGf','https://drive.google.com/file/d/1JWCakoyIsDqppBmDlsSwUxdMnCWg9WGf/view?usp=drivesdk','IMG_5914.JPG','photo',5108,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5914.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1JWCakoyIsDqppBmDlsSwUxdMnCWg9WGf/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1JWCakoyIsDqppBmDlsSwUxdMnCWg9WGf&sz=w1600','DXF-1213'),
('1XJoQi_tDG1O-6QY4WJjf0QRGdA79fhYQ','https://drive.google.com/file/d/1XJoQi_tDG1O-6QY4WJjf0QRGdA79fhYQ/view?usp=drivesdk','IMG_5917.JPG','photo',5109,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5917.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1XJoQi_tDG1O-6QY4WJjf0QRGdA79fhYQ/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1XJoQi_tDG1O-6QY4WJjf0QRGdA79fhYQ&sz=w1600','DXF-1214'),
('1yHYvrrOgQr_p7CFt5RfsZHmWgnuPGZ5Z','https://drive.google.com/file/d/1yHYvrrOgQr_p7CFt5RfsZHmWgnuPGZ5Z/view?usp=drivesdk','IMG_5918.JPG','photo',5110,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5918.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1yHYvrrOgQr_p7CFt5RfsZHmWgnuPGZ5Z/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1yHYvrrOgQr_p7CFt5RfsZHmWgnuPGZ5Z&sz=w1600','DXF-1215'),
('1Q5xYBJEKVM46iSpkf9kxA5Ou7PYEYb_g','https://drive.google.com/file/d/1Q5xYBJEKVM46iSpkf9kxA5Ou7PYEYb_g/view?usp=drivesdk','IMG_5919.JPG','photo',5111,'Drive intake — X image. Artist tier/category review pending. Original file: IMG_5919.JPG','Grizz Exams / X Tha God','https://drive.google.com/file/d/1Q5xYBJEKVM46iSpkf9kxA5Ou7PYEYb_g/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1Q5xYBJEKVM46iSpkf9kxA5Ou7PYEYb_g&sz=w1600','DXF-1216'),
('1lU-ShqWv3BWvqTAyvlIB9fi0IpvDNw6L','https://drive.google.com/file/d/1lU-ShqWv3BWvqTAyvlIB9fi0IpvDNw6L/view?usp=drivesdk','MVI_5931.MOV','video',5112,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: MVI_5931.MOV','Grizz Exams / X Tha God','https://drive.google.com/file/d/1lU-ShqWv3BWvqTAyvlIB9fi0IpvDNw6L/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1lU-ShqWv3BWvqTAyvlIB9fi0IpvDNw6L&sz=w1600','DXF-1217'),
('1Tiu9k_8piYefAWxFSqi-MKafjSgpjnJ5','https://drive.google.com/file/d/1Tiu9k_8piYefAWxFSqi-MKafjSgpjnJ5/view?usp=drivesdk','MVI_5932.MOV','video',5113,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: MVI_5932.MOV','Grizz Exams / X Tha God','https://drive.google.com/file/d/1Tiu9k_8piYefAWxFSqi-MKafjSgpjnJ5/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1Tiu9k_8piYefAWxFSqi-MKafjSgpjnJ5&sz=w1600','DXF-1218'),
('1odw2ajwAnD7gPUcvWOy358p9JH7ZCq8s','https://drive.google.com/file/d/1odw2ajwAnD7gPUcvWOy358p9JH7ZCq8s/view?usp=drivesdk','MVI_5933.MOV','video',5114,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: MVI_5933.MOV','Grizz Exams / X Tha God','https://drive.google.com/file/d/1odw2ajwAnD7gPUcvWOy358p9JH7ZCq8s/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1odw2ajwAnD7gPUcvWOy358p9JH7ZCq8s&sz=w1600','DXF-1219'),
('1kodQ1X8pvoBFjdWWcq709LAW_lZBoaWD','https://drive.google.com/file/d/1kodQ1X8pvoBFjdWWcq709LAW_lZBoaWD/view?usp=drivesdk','MVI_5956.MOV','video',5115,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: MVI_5956.MOV','Grizz Exams / X Tha God','https://drive.google.com/file/d/1kodQ1X8pvoBFjdWWcq709LAW_lZBoaWD/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1kodQ1X8pvoBFjdWWcq709LAW_lZBoaWD&sz=w1600','DXF-1220'),
('1CaVk6puOZV7COo_xlBBt80exDCoi3znS','https://drive.google.com/file/d/1CaVk6puOZV7COo_xlBBt80exDCoi3znS/view?usp=drivesdk','MVI_5957.MOV','video',5116,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: MVI_5957.MOV','Grizz Exams / X Tha God','https://drive.google.com/file/d/1CaVk6puOZV7COo_xlBBt80exDCoi3znS/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1CaVk6puOZV7COo_xlBBt80exDCoi3znS&sz=w1600','DXF-1221'),
('1CWmWWHzI0QmWsLIWFOB2wekVqBDkqGyH','https://drive.google.com/file/d/1CWmWWHzI0QmWsLIWFOB2wekVqBDkqGyH/view?usp=drivesdk','MVI_5958.MOV','video',5117,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: MVI_5958.MOV','Grizz Exams / X Tha God','https://drive.google.com/file/d/1CWmWWHzI0QmWsLIWFOB2wekVqBDkqGyH/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1CWmWWHzI0QmWsLIWFOB2wekVqBDkqGyH&sz=w1600','DXF-1222'),
('19wS_7GwCiZop9DtYbv6gHgK2U0jMhx35','https://drive.google.com/file/d/19wS_7GwCiZop9DtYbv6gHgK2U0jMhx35/view?usp=drivesdk','MVI_5959.MOV','video',5118,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: MVI_5959.MOV','Grizz Exams / X Tha God','https://drive.google.com/file/d/19wS_7GwCiZop9DtYbv6gHgK2U0jMhx35/view?usp=drivesdk','https://drive.google.com/thumbnail?id=19wS_7GwCiZop9DtYbv6gHgK2U0jMhx35&sz=w1600','DXF-1223'),
('1-z6_dEgg9co4qol8e7geD1023AoWHjIc','https://drive.google.com/file/d/1-z6_dEgg9co4qol8e7geD1023AoWHjIc/view?usp=drivesdk','MVI_5960.MOV','video',5119,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: MVI_5960.MOV','Grizz Exams / X Tha God','https://drive.google.com/file/d/1-z6_dEgg9co4qol8e7geD1023AoWHjIc/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1-z6_dEgg9co4qol8e7geD1023AoWHjIc&sz=w1600','DXF-1224'),
('13hVsWKsGc2r4m6u7-bnf4zp_0xV5AbMn','https://drive.google.com/file/d/13hVsWKsGc2r4m6u7-bnf4zp_0xV5AbMn/view?usp=drivesdk','MVI_5961.MOV','video',5120,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: MVI_5961.MOV','Grizz Exams / X Tha God','https://drive.google.com/file/d/13hVsWKsGc2r4m6u7-bnf4zp_0xV5AbMn/view?usp=drivesdk','https://drive.google.com/thumbnail?id=13hVsWKsGc2r4m6u7-bnf4zp_0xV5AbMn&sz=w1600','DXF-1225'),
('1RCezPBbqQyHvpD2cll2IrHxDzzNNORQP','https://drive.google.com/file/d/1RCezPBbqQyHvpD2cll2IrHxDzzNNORQP/view?usp=drivesdk','MVI_5962.MOV','video',5121,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: MVI_5962.MOV','Grizz Exams / X Tha God','https://drive.google.com/file/d/1RCezPBbqQyHvpD2cll2IrHxDzzNNORQP/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1RCezPBbqQyHvpD2cll2IrHxDzzNNORQP&sz=w1600','DXF-1226'),
('1cOonrfQ4kGaonSF0CukzQvedITxTVIHM','https://drive.google.com/file/d/1cOonrfQ4kGaonSF0CukzQvedITxTVIHM/view?usp=drivesdk','MVI_5964.MOV','video',5122,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: MVI_5964.MOV','Grizz Exams / X Tha God','https://drive.google.com/file/d/1cOonrfQ4kGaonSF0CukzQvedITxTVIHM/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1cOonrfQ4kGaonSF0CukzQvedITxTVIHM&sz=w1600','DXF-1227'),
('1Dh73qIK9dqBsXZ5swCMTg45_SzRnu3a8','https://drive.google.com/file/d/1Dh73qIK9dqBsXZ5swCMTg45_SzRnu3a8/view?usp=drivesdk','MVI_5965.MOV','video',5123,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: MVI_5965.MOV','Grizz Exams / X Tha God','https://drive.google.com/file/d/1Dh73qIK9dqBsXZ5swCMTg45_SzRnu3a8/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1Dh73qIK9dqBsXZ5swCMTg45_SzRnu3a8&sz=w1600','DXF-1228'),
('1JmCKDS3N5NWlavSJ8yaL64ykmGZAUcD4','https://drive.google.com/file/d/1JmCKDS3N5NWlavSJ8yaL64ykmGZAUcD4/view?usp=drivesdk','MVI_5966.MOV','video',5124,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: MVI_5966.MOV','Grizz Exams / X Tha God','https://drive.google.com/file/d/1JmCKDS3N5NWlavSJ8yaL64ykmGZAUcD4/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1JmCKDS3N5NWlavSJ8yaL64ykmGZAUcD4&sz=w1600','DXF-1229'),
('1rowrw8Etvq77DK8QAG-16ktVDt9Os9g9','https://drive.google.com/file/d/1rowrw8Etvq77DK8QAG-16ktVDt9Os9g9/view?usp=drivesdk','X Tha God.mov','video',5125,'Drive intake — unclassified X video. Artist tier/category review pending. Original file: X Tha God.mov','High Alert Promo / X Tha God','https://drive.google.com/file/d/1rowrw8Etvq77DK8QAG-16ktVDt9Os9g9/view?usp=drivesdk','https://drive.google.com/thumbnail?id=1rowrw8Etvq77DK8QAG-16ktVDt9Os9g9&sz=w1600','DXF-1230');

INSERT INTO artist_media(
  artist_id,media_type,provider,external_id,canonical_url,title,event_date,
  era_slug,visibility,sort_order,active,description,source_name,source_url,
  thumbnail_url,rights_status,published_at
)
SELECT
  a.id,s.media_type,'google-drive',s.external_id,s.canonical_url,s.title,NULL,
  'tha-x-filez-drive','public',s.sort_order,1,s.description,s.source_name,s.source_url,
  s.thumbnail_url,'first-party-crowd-archive',NULL
FROM _dxf_drive_0024 s
JOIN artists a ON a.artist_slug='x-tha-god'
WHERE NOT EXISTS(
  SELECT 1 FROM artist_media m
  WHERE m.provider='google-drive' AND m.external_id=s.external_id
);

INSERT OR IGNORE INTO media_access_policy(
  media_id,access_state,teaser_mode,cypherz_visible,active
)
SELECT m.id,'public','visible',1,1
FROM artist_media m
JOIN _dxf_drive_0024 s ON s.external_id=m.external_id
WHERE m.provider='google-drive'
  AND m.artist_id=(SELECT id FROM artists WHERE artist_slug='x-tha-god');

UPDATE media_access_policy
SET access_state='public',
    house_slug=NULL,
    unlock_slug=NULL,
    teaser_mode='visible',
    cypherz_visible=1,
    active=1,
    updated_at=CURRENT_TIMESTAMP
WHERE media_id IN (
  SELECT m.id
  FROM artist_media m
  JOIN _dxf_drive_0024 s ON s.external_id=m.external_id
  WHERE m.provider='google-drive'
    AND m.artist_id=(SELECT id FROM artists WHERE artist_slug='x-tha-god')
);

UPDATE artist_media
SET visibility='public'
WHERE provider='google-drive'
  AND external_id IN (SELECT external_id FROM _dxf_drive_0024)
  AND artist_id=(SELECT id FROM artists WHERE artist_slug='x-tha-god');

INSERT OR IGNORE INTO player_media_collection_items(
  collection_id,media_id,file_code,is_primary,sort_order,active
)
SELECT c.id,m.id,s.file_code,1,m.sort_order,1
FROM _dxf_drive_0024 s
JOIN artist_media m ON m.provider='google-drive' AND m.external_id=s.external_id
JOIN player_media_collections c
  ON c.artist_id=m.artist_id AND c.collection_slug='tha-x-filez';

DROP TABLE _dxf_drive_0024;
